FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# SeaRails API

## Sign Up [/register]

### Register [POST]

Registers a new user

+ request (application/json)

        [
            {
                "username":"{{username}}",
                "password":"{{password}}"
            }
        ]
        
+ response 200 (application/json)

        {
            "message":"registered successfully"
        }

+ response 500 (text/plain)
    
        Something went wrong

        
## Blogs [/blogs]

### Get Blogs [GET]

Returns a list of all blogs

+ response 200 (application/json)

        [
            {
                "id":"",
                "title":"",
                "body":"",
                "author":""
                "published_on":"YYYY-MM-DD-HH-MM-SS"
            }
        ]
        
+ response 500 (text/plain)
    
        Something went wrong


### Create new blog [POST]

Creates a new blog post

+ request (application/json)
    + Headers
            
            Authentication: Basic Auth

+ request (application/json)

        
        {
            "title":"{{title}}",
            "body":"{{blog}}"
            "published_on":"YYYY-MM-DD-HH-MM-SS"
        }
        
        
+ response 201 (application/json)

        {
            "message":"Blog created successfully"
        }

+ response 403 (text/plain)

        Permission denied

+ response 500 (text/plain)
    
        Something went wrong
        
## Blog [/blogs/{id}]

+ parameters
    
    + id (number) - id of the blog to be editted

### Retrieve a blog [GET]

Returns a single blog by id

+ request (application/json)

        {
            "id":"{{id}}"
        }
        
        
+ response 200 (application/json)

        {
            "id":"",
            "title":"",
            "body":"",
            "author":""
            "comments":{
                "commenter":"",
                "comment":""
            }
        }
        

+ response 404 (application/json)

        {
            "message":"no such blog"
        }
    
+ response 500 (text/plain)
    
        Something went wrong

### Edit a blog [PATCH]

Updates an existing blog

+ request 
    + Headers
            
            Authentication: Basic Auth

+ request (application/json)

        
        {
            "id":"{{id}}"
        }
       
        
+ response 200 (application/json)

        {
            "message": "edit succesful"
        }

+ response 403 (text/plain)

        Permission Denied

+ response 500 (text/plain)
    
        Something went wrong


### Delete Blog [DELETE]

Deletes an existing post

+ request
    + Headers
            
            Authentication: Basic Auth
 
+ request (application/json)

        {
            "id":"{{id}}"
        }

+ response 200

+ response 403 (application/json)

        {
            "message":"permission denied"
        }

+ response 500 (text/plain)
    
        Something went wrong
   
   
## Comment [/blogs/{blog_id}/comments/{comment_id}]

+ Parameters
    + blog_id (number) - id of the blog having the comment to be editted
    + comment_id (number) - id of the comment to be editted

### Edit Comment [PATCH]

Updates an existing comment

+ request
    + Headers
            
            Authentication: Basic Auth
 

+ request (application/json)

        {
            "blog_id":"{blog_id}",
            "comment_id":"{comment_id}",
            "body":"{body}"
        }
+ response 200 (application/json)

        {
            "success":"editted successfully"
        }
+ response 404 (application/json)

        {
            "error":"resource not found"
        }
+ response 403 (application/json)

        {
            "message":"permission denied"
        }
        
+ response 500 (text/plain)
    
        Something went wrong
   
### Delete Comment [DELETE]

Deletes a comment

+ request 
    + Headers
            
            Authentication: Basic Auth
        
+ request (application/json)

        {
            "blog_id":"{{blog_id}}",
            "comment_id":"{comment_id}"
        }

+ response 200 (application/json)

        {
            "message":"Deleted successfully"
        }
        
+ response 403 (application/json)

        {
            "message":"permission denied"
        }
        
+ response 500 (text/plain)
    
        Something went wrong