FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# SeaRails API

## Sign Up [/register]

### Register [POST]

+ request (application/json)

        [
            {
                "username":"{{username}}",
                "password":{{password}}
            }
        ]
        
+ response 200 (application/json)

        [
            {
                "token":""
            }
        ]
        
## New Blog [/blogs/new]

### Create new blog [POST]

Create a new blog post

+ request (application/json)

        [
            {
                "title":"{{title}}",
                "body":"{{blog}}"
            }
        ]
        
+ response 200 (application/json)

        [
            {
                "title":"sample title",
                "body":"sample body"
            }
        ]
        
## Blogs [/blogs]

### Get Blogs [GET]

Get a list of all blogs

+ response 200 (application/json)

        [
            {
                "id":"",
                "title":"",
                "body":"",
                "author":""
                "comments":{
                    "commenter":"",
                    "comment":""
                }
            }
        ]

## Blog [/blogs/{id}]

### Edit a blog [PATCH]

Edit an existing blog.

+ parameters
    
    + id (number) - id of the blog to be editted

+ request (application/json)

        [
            {
                "title":"{{new_title}}",
                "body":"{{new_body}}"
            }
        ]
        
+ response 200 (application/json)

### Delete Blog [DELETE]
Delete an existing post

+ request (application/json)

        {
            "id":"{{}}"
        }

+ response 200

+ response 403 (application/json)

        {
            "message":"permission denied"
        }
        
## Comment [/blogs/{blog_id}/comments/{comment_id}]


+ Parameters
    + blog_id (number) - id of the blog having the comment to be editted
    + comment_id (number) - id of the comment to be editted

### Edit Comment [PATCH]

Edit an existing comment


+ request (application/json)

        {
            "blog_id":"{blog_id}",
            "comment_id":"{comment_id}",
            "body":"{body}"
        }
+ response 200 (application/json)

        {
            "success":"editted successfully"
        }
+ response 404

        {
            "error":"resource not found"
        }
+ response 403 

        {
            "message":"permission denied"
        }
### Delete Comment [DELETE]

+ request (application/json)

        [
            "id":"{{}}"
        ]

+ response 200 (application/json)

        [
            "success":""
        ]
        
+ response 403 

        [
            "message":"permission denied"
        ]